apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 2
  selector:
    app: docker-jenkins
  template:
    metadata:
      labels:
        app: docker-jenkins
    spec:
      containers:
      - name: docker-jenkins
        image: docker-jenkins:v3
        ports:
        - containerPort: 8070