## Nodeport
apiVersion: v1
kind: Service
metadata:
  name: hello-deploy
  namespace: default
  labels:
    app: docker-jenkins
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 8070
    targetPort: 80
  selector:
    app: docker-jenkins

# LoadBalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-svc
#  namespace: default
#  labels:
#    app: docker-jenkins
#spec:
#  type: LoadBalancer
#  ports:
#  - port: 8070
#    protocol: TCP
#    targetPort: 8070
#    nodePort: 31010
#  selector:
#    app: docker-jenkins

# LoadBalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-svc
#  namespace: default
#  labels:
#    app: docker-jenkins
#spec:
#  type: LoadBalancer
#  ports:
#  - port: 8070
#    protocol: TCP
#    targetPort: 80
#  selector:
#    app: docker-jenkins
#  externalTrafficPolicy: Local