---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.fullName }}
  labels:
    app: {{ .Values.fullName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullName }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullName }}
    spec:
      containers:
      - name: {{ .Values.fullName }}
        image: {{.Values.ImageName}}:{{ .Values.tag }}
        ports:
        - containerPort: {{ .Values.port }}
