---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: hello-deploy
  labels:
    app: docker-jenkins
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: docker-jenkins
  template:
    metadata:
      labels:
        app: docker-jenkins
    spec:
      containers:
      - name: docker-jenkins
        image: {{.Values.ImageName}}:{{ .Values.tag }}
        ports:
        - containerPort: 8070
