---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: docker-jenkins
  ports:
  - protocol: TCP
    port: 8070

