apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: docker-jenkins
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8070
    nodePort: 30001
    protocol: TCP
  selector:
    app: docker-jenkins