apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-resource-1
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: nginx-deploy-blue
          servicePort: 80